# https://archlinuxarm.org/forum/viewtopic.php?f=15&t=17007&p=72789
# https://github.com/pikvm/pikvm/issues/1375
# https://github.com/pikvm/pikvm/issues/1604
# https://github.com/RPi-Distro/firmware-nonfree/commit/e1e78b65b350c799cb7cac49713e21c79fcf993d
# https://github.com/raspberrypi/linux/issues/4718
options brcmfmac roamoff=1 feature_disable=0x282000
