location = /extras/webterm/ttyd/ws {
	proxy_pass http://ttyd/ws;
	include /etc/kvmd/nginx/loc-proxy.conf;
	include /etc/kvmd/nginx/loc-websocket.conf;
}

location /extras/webterm/ttyd/ {
	proxy_pass http://ttyd/;
	include /etc/kvmd/nginx/loc-login.conf;
	include /etc/kvmd/nginx/loc-proxy.conf;
	include /etc/kvmd/nginx/loc-nocache.conf;
}
